[package]
name = "Rust"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
env_logger = "0.11.10"
log = "0.4.30"
ordered-float = { version = "5.3.0", features = ["serde"] }
rdev = { version = "0.5.3", features = ["serialize"] }
serde = { version = "1.0.228", features = ["rc", "serde_derive"] }
serde_yaml = "0.9.34"
strum = { version = "0.28.0", features = ["derive"] }
thread-priority = "3.0.0"


[[bin]]
name = "hk-rs"
path = "src/main.rs"
