use serde::{Deserialize, Deserializer, Serialize, Serializer};
use std::str::FromStr;
use strum::Display;

#[derive(Display, Debug, Copy, Clone, PartialEq, Eq, Hash)]
pub enum Key {
    /// Alt key on Linux and Windows (option key on macOS)
    Alt,
    AltGr,
    Backspace,
    CapsLock,
    #[strum(serialize = "Ctrl")]
    Control, // special key that refers to either one of ControlLeft or ControlRight
    #[strum(serialize = "CtrlL")]
    ControlLeft,
    #[strum(serialize = "CtrlR")]
    ControlRight,
    #[strum(serialize = "Del")]
    Delete,
    DownArrow,
    End,
    #[strum(serialize = "Esc")]
    Escape,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    Home,
    LeftArrow,
    /// also known as "windows", "super", and "command"
    MetaLeft,
    /// also known as "windows", "super", and "command"
    MetaRight,
    PageDown,
    PageUp,
    Return,
    RightArrow,
    Shift, // Special key that refers to either of ShiftLeft or ShiftRight
    ShiftLeft,
    ShiftRight,
    Space,
    Tab,
    UpArrow,
    PrintScreen,
    ScrollLock,
    Pause,
    NumLock,
    BackQuote,
    #[strum(serialize = "1")]
    Num1,
    #[strum(serialize = "2")]
    Num2,
    #[strum(serialize = "3")]
    Num3,
    #[strum(serialize = "4")]
    Num4,
    #[strum(serialize = "5")]
    Num5,
    #[strum(serialize = "6")]
    Num6,
    #[strum(serialize = "7")]
    Num7,
    #[strum(serialize = "8")]
    Num8,
    #[strum(serialize = "9")]
    Num9,
    #[strum(serialize = "0")]
    Num0,
    #[strum(serialize = "-")]
    Minus,
    #[strum(serialize = "=")]
    Equal,
    Q,
    W,
    E,
    R,
    T,
    Y,
    U,
    I,
    O,
    P,
    #[strum(serialize = "[")]
    LeftBracket,
    #[strum(serialize = "]")]
    RightBracket,
    A,
    S,
    D,
    F,
    G,
    H,
    J,
    K,
    L,
    #[strum(serialize = ";")]
    SemiColon,
    #[strum(serialize = "'")]
    Quote,
    #[strum(serialize = "\\")]
    BackSlash,
    IntlBackslash,
    Z,
    X,
    C,
    V,
    B,
    N,
    M,
    #[strum(serialize = ",")]
    Comma,
    #[strum(serialize = ".")]
    Dot,
    #[strum(serialize = "/")]
    Slash,
    Insert,
    KpReturn,
    KpMinus,
    KpPlus,
    KpMultiply,
    KpDivide,
    Kp0,
    Kp1,
    Kp2,
    Kp3,
    Kp4,
    Kp5,
    Kp6,
    Kp7,
    Kp8,
    Kp9,
    KpDelete,
    Function,
    MouseLeft,
    MouseRight,
    MouseMiddle,
    Unknown(u32),
}

impl Serialize for Key {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(&self.to_string())
    }
}

impl<'de> Deserialize<'de> for Key {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        Key::from_str(&s).map_err(serde::de::Error::custom)
    }
}

impl FromStr for Key {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "Alt" => Ok(Key::Alt),
            "AltGr" => Ok(Key::AltGr),
            "Backspace" => Ok(Key::Backspace),
            "CapsLock" => Ok(Key::CapsLock),
            "Ctrl" | "Control" => Ok(Key::Control),
            "CtrlL" | "ControlLeft" => Ok(Key::ControlLeft),
            "CtrlR" | "ControlRight" => Ok(Key::ControlRight),
            "Del" | "Delete" => Ok(Key::Delete),
            "DownArrow" => Ok(Key::DownArrow),
            "End" => Ok(Key::End),
            "Esc" | "Escape" => Ok(Key::Escape),
            "F1" => Ok(Key::F1),
            "F2" => Ok(Key::F2),
            "F3" => Ok(Key::F3),
            "F4" => Ok(Key::F4),
            "F5" => Ok(Key::F5),
            "F6" => Ok(Key::F6),
            "F7" => Ok(Key::F7),
            "F8" => Ok(Key::F8),
            "F9" => Ok(Key::F9),
            "F10" => Ok(Key::F10),
            "F11" => Ok(Key::F11),
            "F12" => Ok(Key::F12),
            "Home" => Ok(Key::Home),
            "LeftArrow" => Ok(Key::LeftArrow),
            "MetaLeft" => Ok(Key::MetaLeft),
            "MetaRight" => Ok(Key::MetaRight),
            "PageDown" => Ok(Key::PageDown),
            "PageUp" => Ok(Key::PageUp),
            "Return" => Ok(Key::Return),
            "RightArrow" => Ok(Key::RightArrow),
            "Shift" => Ok(Key::Shift),
            "ShiftLeft" => Ok(Key::ShiftLeft),
            "ShiftRight" => Ok(Key::ShiftRight),
            "Space" => Ok(Key::Space),
            "Tab" => Ok(Key::Tab),
            "UpArrow" => Ok(Key::UpArrow),
            "PrintScreen" => Ok(Key::PrintScreen),
            "ScrollLock" => Ok(Key::ScrollLock),
            "Pause" => Ok(Key::Pause),
            "NumLock" => Ok(Key::NumLock),
            "BackQuote" => Ok(Key::BackQuote),
            "1" | "Num1" => Ok(Key::Num1),
            "2" | "Num2" => Ok(Key::Num2),
            "3" | "Num3" => Ok(Key::Num3),
            "4" | "Num4" => Ok(Key::Num4),
            "5" | "Num5" => Ok(Key::Num5),
            "6" | "Num6" => Ok(Key::Num6),
            "7" | "Num7" => Ok(Key::Num7),
            "8" | "Num8" => Ok(Key::Num8),
            "9" | "Num9" => Ok(Key::Num9),
            "0" | "Num0" => Ok(Key::Num0),
            "-" | "Minus" => Ok(Key::Minus),
            "=" | "Equal" => Ok(Key::Equal),
            "Q" => Ok(Key::Q),
            "W" => Ok(Key::W),
            "E" => Ok(Key::E),
            "R" => Ok(Key::R),
            "T" => Ok(Key::T),
            "Y" => Ok(Key::Y),
            "U" => Ok(Key::U),
            "I" => Ok(Key::I),
            "O" => Ok(Key::O),
            "P" => Ok(Key::P),
            "[" | "LeftBracket" => Ok(Key::LeftBracket),
            "]" | "RightBracket" => Ok(Key::RightBracket),
            "A" => Ok(Key::A),
            "S" => Ok(Key::S),
            "D" => Ok(Key::D),
            "F" => Ok(Key::F),
            "G" => Ok(Key::G),
            "H" => Ok(Key::H),
            "J" => Ok(Key::J),
            "K" => Ok(Key::K),
            "L" => Ok(Key::L),
            ";" | "SemiColon" => Ok(Key::SemiColon),
            "'" | "Quote" => Ok(Key::Quote),
            "\\" | "BackSlash" => Ok(Key::BackSlash),
            "IntlBackslash" => Ok(Key::IntlBackslash),
            "Z" => Ok(Key::Z),
            "X" => Ok(Key::X),
            "C" => Ok(Key::C),
            "V" => Ok(Key::V),
            "B" => Ok(Key::B),
            "N" => Ok(Key::N),
            "M" => Ok(Key::M),
            "," | "Comma" => Ok(Key::Comma),
            "." | "Dot" => Ok(Key::Dot),
            "/" | "Slash" => Ok(Key::Slash),
            "Insert" => Ok(Key::Insert),
            "KpReturn" => Ok(Key::KpReturn),
            "KpMinus" => Ok(Key::KpMinus),
            "KpPlus" => Ok(Key::KpPlus),
            "KpMultiply" => Ok(Key::KpMultiply),
            "KpDivide" => Ok(Key::KpDivide),
            "Kp0" => Ok(Key::Kp0),
            "Kp1" => Ok(Key::Kp1),
            "Kp2" => Ok(Key::Kp2),
            "Kp3" => Ok(Key::Kp3),
            "Kp4" => Ok(Key::Kp4),
            "Kp5" => Ok(Key::Kp5),
            "Kp6" => Ok(Key::Kp6),
            "Kp7" => Ok(Key::Kp7),
            "Kp8" => Ok(Key::Kp8),
            "Kp9" => Ok(Key::Kp9),
            "KpDelete" => Ok(Key::KpDelete),
            "Function" => Ok(Key::Function),
            "M1" | "MouseLeft" => Ok(Key::MouseLeft),
            "M2" | "MouseRight" => Ok(Key::MouseRight),
            "M3" | "MouseMiddle" => Ok(Key::MouseMiddle),
            "Unknown" => Err("Unknown key requires a u32 code".to_string()),
            _ => Err(format!("Unknown key: {}", s)),
        }
    }
}

pub enum Rdev {
    Key(rdev::Key),
    Button(rdev::Button),
}

impl From<Key> for Rdev {
    fn from(value: Key) -> Self {
        match value {
            Key::Alt => Rdev::Key(rdev::Key::Alt),
            Key::AltGr => Rdev::Key(rdev::Key::AltGr),
            Key::Backspace => Rdev::Key(rdev::Key::Backspace),
            Key::CapsLock => Rdev::Key(rdev::Key::CapsLock),
            Key::Control => Rdev::Key(rdev::Key::ControlLeft), // Default to left control for the generic Control key
            Key::ControlLeft => Rdev::Key(rdev::Key::ControlLeft),
            Key::ControlRight => Rdev::Key(rdev::Key::ControlRight),
            Key::Delete => Rdev::Key(rdev::Key::Delete),
            Key::DownArrow => Rdev::Key(rdev::Key::DownArrow),
            Key::End => Rdev::Key(rdev::Key::End),
            Key::Escape => Rdev::Key(rdev::Key::Escape),
            Key::F1 => Rdev::Key(rdev::Key::F1),
            Key::F2 => Rdev::Key(rdev::Key::F2),
            Key::F3 => Rdev::Key(rdev::Key::F3),
            Key::F4 => Rdev::Key(rdev::Key::F4),
            Key::F5 => Rdev::Key(rdev::Key::F5),
            Key::F6 => Rdev::Key(rdev::Key::F6),
            Key::F7 => Rdev::Key(rdev::Key::F7),
            Key::F8 => Rdev::Key(rdev::Key::F8),
            Key::F9 => Rdev::Key(rdev::Key::F9),
            Key::F10 => Rdev::Key(rdev::Key::F10),
            Key::F11 => Rdev::Key(rdev::Key::F11),
            Key::F12 => Rdev::Key(rdev::Key::F12),
            Key::Home => Rdev::Key(rdev::Key::Home),
            Key::LeftArrow => Rdev::Key(rdev::Key::LeftArrow),
            Key::MetaLeft => Rdev::Key(rdev::Key::MetaLeft),
            Key::MetaRight => Rdev::Key(rdev::Key::MetaRight),
            Key::PageDown => Rdev::Key(rdev::Key::PageDown),
            Key::PageUp => Rdev::Key(rdev::Key::PageUp),
            Key::Return => Rdev::Key(rdev::Key::Return),
            Key::RightArrow => Rdev::Key(rdev::Key::RightArrow),
            Key::Shift => Rdev::Key(rdev::Key::ShiftLeft), // Default to left shift for the generic Shift key
            Key::ShiftLeft => Rdev::Key(rdev::Key::ShiftLeft),
            Key::ShiftRight => Rdev::Key(rdev::Key::ShiftRight),
            Key::Space => Rdev::Key(rdev::Key::Space),
            Key::Tab => Rdev::Key(rdev::Key::Tab),
            Key::UpArrow => Rdev::Key(rdev::Key::UpArrow),
            Key::PrintScreen => Rdev::Key(rdev::Key::PrintScreen),
            Key::ScrollLock => Rdev::Key(rdev::Key::ScrollLock),
            Key::Pause => Rdev::Key(rdev::Key::Pause),
            Key::NumLock => Rdev::Key(rdev::Key::NumLock),
            Key::BackQuote => Rdev::Key(rdev::Key::BackQuote),
            Key::Num1 => Rdev::Key(rdev::Key::Num1),
            Key::Num2 => Rdev::Key(rdev::Key::Num2),
            Key::Num3 => Rdev::Key(rdev::Key::Num3),
            Key::Num4 => Rdev::Key(rdev::Key::Num4),
            Key::Num5 => Rdev::Key(rdev::Key::Num5),
            Key::Num6 => Rdev::Key(rdev::Key::Num6),
            Key::Num7 => Rdev::Key(rdev::Key::Num7),
            Key::Num8 => Rdev::Key(rdev::Key::Num8),
            Key::Num9 => Rdev::Key(rdev::Key::Num9),
            Key::Num0 => Rdev::Key(rdev::Key::Num0),
            Key::Minus => Rdev::Key(rdev::Key::Minus),
            Key::Equal => Rdev::Key(rdev::Key::Equal),
            Key::Q => Rdev::Key(rdev::Key::KeyQ),
            Key::W => Rdev::Key(rdev::Key::KeyW),
            Key::E => Rdev::Key(rdev::Key::KeyE),
            Key::R => Rdev::Key(rdev::Key::KeyR),
            Key::T => Rdev::Key(rdev::Key::KeyT),
            Key::Y => Rdev::Key(rdev::Key::KeyY),
            Key::U => Rdev::Key(rdev::Key::KeyU),
            Key::I => Rdev::Key(rdev::Key::KeyI),
            Key::O => Rdev::Key(rdev::Key::KeyO),
            Key::P => Rdev::Key(rdev::Key::KeyP),
            Key::LeftBracket => Rdev::Key(rdev::Key::LeftBracket),
            Key::RightBracket => Rdev::Key(rdev::Key::RightBracket),
            Key::A => Rdev::Key(rdev::Key::KeyA),
            Key::S => Rdev::Key(rdev::Key::KeyS),
            Key::D => Rdev::Key(rdev::Key::KeyD),
            Key::F => Rdev::Key(rdev::Key::KeyF),
            Key::G => Rdev::Key(rdev::Key::KeyG),
            Key::H => Rdev::Key(rdev::Key::KeyH),
            Key::J => Rdev::Key(rdev::Key::KeyJ),
            Key::K => Rdev::Key(rdev::Key::KeyK),
            Key::L => Rdev::Key(rdev::Key::KeyL),
            Key::SemiColon => Rdev::Key(rdev::Key::SemiColon),
            Key::Quote => Rdev::Key(rdev::Key::Quote),
            Key::BackSlash => Rdev::Key(rdev::Key::BackSlash),
            Key::IntlBackslash => Rdev::Key(rdev::Key::IntlBackslash),
            Key::Z => Rdev::Key(rdev::Key::KeyZ),
            Key::X => Rdev::Key(rdev::Key::KeyX),
            Key::C => Rdev::Key(rdev::Key::KeyC),
            Key::V => Rdev::Key(rdev::Key::KeyV),
            Key::B => Rdev::Key(rdev::Key::KeyB),
            Key::N => Rdev::Key(rdev::Key::KeyN),
            Key::M => Rdev::Key(rdev::Key::KeyM),
            Key::Comma => Rdev::Key(rdev::Key::Comma),
            Key::Dot => Rdev::Key(rdev::Key::Dot),
            Key::Slash => Rdev::Key(rdev::Key::Slash),
            Key::Insert => Rdev::Key(rdev::Key::Insert),
            Key::KpReturn => Rdev::Key(rdev::Key::KpReturn),
            Key::KpMinus => Rdev::Key(rdev::Key::KpMinus),
            Key::KpPlus => Rdev::Key(rdev::Key::KpPlus),
            Key::KpMultiply => Rdev::Key(rdev::Key::KpMultiply),
            Key::KpDivide => Rdev::Key(rdev::Key::KpDivide),
            Key::Kp0 => Rdev::Key(rdev::Key::Kp0),
            Key::Kp1 => Rdev::Key(rdev::Key::Kp1),
            Key::Kp2 => Rdev::Key(rdev::Key::Kp2),
            Key::Kp3 => Rdev::Key(rdev::Key::Kp3),
            Key::Kp4 => Rdev::Key(rdev::Key::Kp4),
            Key::Kp5 => Rdev::Key(rdev::Key::Kp5),
            Key::Kp6 => Rdev::Key(rdev::Key::Kp6),
            Key::Kp7 => Rdev::Key(rdev::Key::Kp7),
            Key::Kp8 => Rdev::Key(rdev::Key::Kp8),
            Key::Kp9 => Rdev::Key(rdev::Key::Kp9),
            Key::KpDelete => Rdev::Key(rdev::Key::KpDelete),
            Key::Function => Rdev::Key(rdev::Key::Function),
            Key::MouseLeft => Rdev::Button(rdev::Button::Left),
            Key::MouseRight => Rdev::Button(rdev::Button::Right),
            Key::MouseMiddle => Rdev::Button(rdev::Button::Middle),
            Key::Unknown(code) => Rdev::Key(rdev::Key::Unknown(code)),
        }
    }
}

impl From<rdev::Key> for Key {
    fn from(value: rdev::Key) -> Self {
        match value {
            rdev::Key::Alt => Key::Alt,
            rdev::Key::AltGr => Key::AltGr,
            rdev::Key::Backspace => Key::Backspace,
            rdev::Key::CapsLock => Key::CapsLock,
            rdev::Key::ControlLeft => Key::ControlLeft,
            rdev::Key::ControlRight => Key::ControlRight,
            rdev::Key::Delete => Key::Delete,
            rdev::Key::DownArrow => Key::DownArrow,
            rdev::Key::End => Key::End,
            rdev::Key::Escape => Key::Escape,
            rdev::Key::F1 => Key::F1,
            rdev::Key::F2 => Key::F2,
            rdev::Key::F3 => Key::F3,
            rdev::Key::F4 => Key::F4,
            rdev::Key::F5 => Key::F5,
            rdev::Key::F6 => Key::F6,
            rdev::Key::F7 => Key::F7,
            rdev::Key::F8 => Key::F8,
            rdev::Key::F9 => Key::F9,
            rdev::Key::F10 => Key::F10,
            rdev::Key::F11 => Key::F11,
            rdev::Key::F12 => Key::F12,
            rdev::Key::Home => Key::Home,
            rdev::Key::LeftArrow => Key::LeftArrow,
            rdev::Key::MetaLeft => Key::MetaLeft,
            rdev::Key::MetaRight => Key::MetaRight,
            rdev::Key::PageDown => Key::PageDown,
            rdev::Key::PageUp => Key::PageUp,
            rdev::Key::Return => Key::Return,
            rdev::Key::RightArrow => Key::RightArrow,
            rdev::Key::ShiftLeft => Key::ShiftLeft,
            rdev::Key::ShiftRight => Key::ShiftRight,
            rdev::Key::Space => Key::Space,
            rdev::Key::Tab => Key::Tab,
            rdev::Key::UpArrow => Key::UpArrow,
            rdev::Key::PrintScreen => Key::PrintScreen,
            rdev::Key::ScrollLock => Key::ScrollLock,
            rdev::Key::Pause => Key::Pause,
            rdev::Key::NumLock => Key::NumLock,
            rdev::Key::BackQuote => Key::BackQuote,
            rdev::Key::Num1 => Key::Num1,
            rdev::Key::Num2 => Key::Num2,
            rdev::Key::Num3 => Key::Num3,
            rdev::Key::Num4 => Key::Num4,
            rdev::Key::Num5 => Key::Num5,
            rdev::Key::Num6 => Key::Num6,
            rdev::Key::Num7 => Key::Num7,
            rdev::Key::Num8 => Key::Num8,
            rdev::Key::Num9 => Key::Num9,
            rdev::Key::Num0 => Key::Num0,
            rdev::Key::Minus => Key::Minus,
            rdev::Key::Equal => Key::Equal,
            rdev::Key::KeyQ => Key::Q,
            rdev::Key::KeyW => Key::W,
            rdev::Key::KeyE => Key::E,
            rdev::Key::KeyR => Key::R,
            rdev::Key::KeyT => Key::T,
            rdev::Key::KeyY => Key::Y,
            rdev::Key::KeyU => Key::U,
            rdev::Key::KeyI => Key::I,
            rdev::Key::KeyO => Key::O,
            rdev::Key::KeyP => Key::P,
            rdev::Key::LeftBracket => Key::LeftBracket,
            rdev::Key::RightBracket => Key::RightBracket,
            rdev::Key::KeyA => Key::A,
            rdev::Key::KeyS => Key::S,
            rdev::Key::KeyD => Key::D,
            rdev::Key::KeyF => Key::F,
            rdev::Key::KeyG => Key::G,
            rdev::Key::KeyH => Key::H,
            rdev::Key::KeyJ => Key::J,
            rdev::Key::KeyK => Key::K,
            rdev::Key::KeyL => Key::L,
            rdev::Key::SemiColon => Key::SemiColon,
            rdev::Key::Quote => Key::Quote,
            rdev::Key::BackSlash => Key::BackSlash,
            rdev::Key::IntlBackslash => Key::IntlBackslash,
            rdev::Key::KeyZ => Key::Z,
            rdev::Key::KeyX => Key::X,
            rdev::Key::KeyC => Key::C,
            rdev::Key::KeyV => Key::V,
            rdev::Key::KeyB => Key::B,
            rdev::Key::KeyN => Key::N,
            rdev::Key::KeyM => Key::M,
            rdev::Key::Comma => Key::Comma,
            rdev::Key::Dot => Key::Dot,
            rdev::Key::Slash => Key::Slash,
            rdev::Key::Insert => Key::Insert,
            rdev::Key::KpReturn => Key::KpReturn,
            rdev::Key::KpMinus => Key::KpMinus,
            rdev::Key::KpPlus => Key::KpPlus,
            rdev::Key::KpMultiply => Key::KpMultiply,
            rdev::Key::KpDivide => Key::KpDivide,
            rdev::Key::Kp0 => Key::Kp0,
            rdev::Key::Kp1 => Key::Kp1,
            rdev::Key::Kp2 => Key::Kp2,
            rdev::Key::Kp3 => Key::Kp3,
            rdev::Key::Kp4 => Key::Kp4,
            rdev::Key::Kp5 => Key::Kp5,
            rdev::Key::Kp6 => Key::Kp6,
            rdev::Key::Kp7 => Key::Kp7,
            rdev::Key::Kp8 => Key::Kp8,
            rdev::Key::Kp9 => Key::Kp9,
            rdev::Key::KpDelete => Key::KpDelete,
            rdev::Key::Function => Key::Function,
            rdev::Key::Unknown(code) => Key::Unknown(code),
        }
    }
}
